version: '3'
services:
    node1:
        build:
            context: .
            dockerfile: Dockerfile.node1
        networks:
            static-network:
                ipv4_address: 172.20.128.1
    node2:
        build:
            context: .
            dockerfile: Dockerfile.node2
        restart: on-failure
        depends_on:
            - "node1"
        networks:
            static-network:
                ipv4_address: 172.20.128.2
    node3:
        build:
            context: .
            dockerfile: Dockerfile.node3
        restart: on-failure
        depends_on:
            - "node1"
        networks:
            static-network:
                ipv4_address: 172.20.128.3
    node4:
        build:
            context: .
            dockerfile: Dockerfile.node4
        restart: on-failure
        depends_on:
            - "node1"
        networks:
            static-network:
                ipv4_address: 172.20.128.4
    node5:
        build:
            context: .
            dockerfile: Dockerfile.node5
        restart: on-failure
        depends_on:
            - "node1"
        networks:
            static-network:
                ipv4_address: 172.20.128.5
networks:
    static-network:
        ipam:
            config:
                - subnet: 172.20.0.0/16